/** Target languages for Google Translate (code + endonym). Sorted by approximate global use. */
const GLOSSA_LANGUAGES = [
  { code: 'en', name: 'English' },
  { code: 'zh-CN', name: '中文 (简体)' },
  { code: 'zh-TW', name: '中文 (繁體)' },
  { code: 'hi', name: 'हिन्दी' },
  { code: 'es', name: 'Español' },
  { code: 'fr', name: 'Français' },
  { code: 'ar', name: 'العربية' },
  { code: 'bn', name: 'বাংলা' },
  { code: 'pt', name: 'Português' },
  { code: 'ru', name: 'Русский' },
  { code: 'ur', name: 'اردو' },
  { code: 'id', name: 'Bahasa Indonesia' },
  { code: 'de', name: 'Deutsch' },
  { code: 'ja', name: '日本語' },
  { code: 'sw', name: 'Kiswahili' },
  { code: 'mr', name: 'मराठी' },
  { code: 'te', name: 'తెలుగు' },
  { code: 'tr', name: 'Türkçe' },
  { code: 'ta', name: 'தமிழ்' },
  { code: 'vi', name: 'Tiếng Việt' },
  { code: 'ko', name: '한국어' },
  { code: 'it', name: 'Italiano' },
  { code: 'th', name: 'ไทย' },
  { code: 'gu', name: 'ગુજરાતી' },
  { code: 'pl', name: 'Polski' },
  { code: 'uk', name: 'Українська' },
  { code: 'fa', name: 'فارسی' },
  { code: 'ms', name: 'Bahasa Melayu' },
  { code: 'nl', name: 'Nederlands' },
  { code: 'ro', name: 'Română' },
  { code: 'pa', name: 'ਪੰਜਾਬੀ' },
  { code: 'el', name: 'Ελληνικά' },
  { code: 'cs', name: 'Čeština' },
  { code: 'sv', name: 'Svenska' },
  { code: 'hu', name: 'Magyar' },
  { code: 'he', name: 'עברית' },
  { code: 'da', name: 'Dansk' },
  { code: 'fi', name: 'Suomi' },
  { code: 'no', name: 'Norsk' },
  { code: 'sk', name: 'Slovenčina' },
  { code: 'hr', name: 'Hrvatski' },
  { code: 'bg', name: 'Български' },
  { code: 'sr', name: 'Српски' },
  { code: 'ca', name: 'Català' },
  { code: 'fil', name: 'Filipino' },
  { code: 'kn', name: 'ಕನ್ನಡ' },
  { code: 'ml', name: 'മലയാളം' },
  { code: 'ha', name: 'Hausa' },
  { code: 'am', name: 'አማርኛ' },
  { code: 'ne', name: 'नेपाली' },
  { code: 'si', name: 'සිංහල' },
  { code: 'km', name: 'ខ្មែរភាសា' },
  { code: 'my', name: 'မြန်မာ' },
  { code: 'ka', name: 'ქართული' },
  { code: 'az', name: 'Azərbaycanca' },
  { code: 'uz', name: 'Oʻzbek' },
  { code: 'kk', name: 'Қазақ' },
  { code: 'be', name: 'Беларуская' },
  { code: 'lt', name: 'Lietuvių' },
  { code: 'lv', name: 'Latviešu' },
  { code: 'et', name: 'Eesti' },
  { code: 'sl', name: 'Slovenščina' },
  { code: 'af', name: 'Afrikaans' },
  { code: 'hy', name: 'Հայերեն' },
  { code: 'mk', name: 'Македонски' },
  { code: 'sq', name: 'Shqip' },
  { code: 'bs', name: 'Bosanski' },
  { code: 'mn', name: 'Монгол' },
  { code: 'ps', name: 'پښتو' },
  { code: 'so', name: 'Soomaali' },
  { code: 'yo', name: 'Yorùbá' },
  { code: 'ig', name: 'Igbo' },
  { code: 'mg', name: 'Malagasy' },
  { code: 'cy', name: 'Cymraeg' },
  { code: 'eu', name: 'Euskara' },
  { code: 'gl', name: 'Galego' },
  { code: 'zu', name: 'isiZulu' },
  { code: 'xh', name: 'isiXhosa' },
  { code: 'lo', name: 'ລາວ' },
  { code: 'jw', name: 'Basa Jawa' },
  { code: 'su', name: 'Basa Sunda' },
  { code: 'ceb', name: 'Cebuano' },
  { code: 'ht', name: 'Kreyòl ayisyen' },
  { code: 'is', name: 'Íslenska' },
  { code: 'ga', name: 'Gaeilge' },
  { code: 'mt', name: 'Malti' },
  { code: 'la', name: 'Latina' },
];
